id_surat = {
        "Al-Fatihah (Pembukaan)":"1",
        "Al-Baqarah (Sapi Betina)":"2",
        "Ali Imran (Keluarga Imran)":"3",
        "An-Nisaa (Wanita)":"4",
        "Al-Ma'idah (Hidangan / Jamuan Makanan)":"5",
        "Al-An'am (Binatang Ternakan)":"6",
        "Al-A'raf (Tempat Yang Tertinggi)":"7",
        "Al-Anfal (Harta Rampasan Perang)":"8",
        "At-Taubah (Pengampunan)":"9",
        "Yunus (Nabi Yunus)":"10",
        "Hud (Nabi Hud)":"11",
        "Yusuf (Nabi Yusuf)":"12",
        "Ar-Ra’d (Guruh / Petir)":"13",
        "Ibrahim (Nabi Ibrahim)":"14",
        "Al-Hijr (Gunung Al Hijr)":"15",
        "An-Nahl (Lebah)":"16",
        "Al-Isra (Perjalanan Malam)":"17",
        "Al-Kahf (Penghuni-Penghuni Gua)":"18",
        "Maryam":"19",
        "Ta Ha":"20",
        "Al-Anbiya (Nabi-Nabi)":"21",
        "Al-Hajj (Haji)":"22",
        "Al-Mu’minun (Orang-Orang Mukmin)":"23",
        "An-Nur (Cahaya)":"24",
        "Al-Furqan (Pembeda)":"25",
        "Asy-Syu’ara (Penyair)":"26",
        "An-Naml (Semut)":"27",
        "Al-Qasas (Kisah)":"28",
        "Al-‘Ankabut (Laba-Laba)":"29",
        "Ar-Rum (Bangsa Romawi)":"30",
        "Luqman (Keluarga Luqman)":"31",
        "As-Sajdah (Sajdah)":"32",
        "Al-Ahzab (Golongan-Golongan Yang Bersekutu)":"33",
        "Saba (Kaum Saba)":"34",
        "Fatir (Pencipta)":"35",
        "Ya Sin (Yaasiin)":"36",
        "As-Saffat (Barisan-Barisan)":"37",
        "Sad (Shaad)":"38",
        "Az-Zumar (Rombongan-Rombongan)":"39",
        "Al-Mu’min/Ghafir (Orang Beriman, Pengampun)":"40",
        "Fussilat (Yang Dijelaskan)":"41",
        "Asy-Syuraa (Musyawarah)":"42",
        "Az-Zukhruf (Perhiasan)":"43",
        "Ad-Dukhan (Kabut)":"44",
        "Al-Jasiyah (Yang Bertekuk Lutut)":"45",
        "Al-Ahqaf (Bukit-Bukit Pasir)":"46",
        "Muhammad (Nabi Muhammad)":"47",
        "Al-Fath (Kemenangan)":"48",
        "Al-Hujurat (Kamar-Kamar)":"49",
        "Qaf":"50",
        "Az-Zariyat (Angin Yang Menerbangkan)":"51",
        "At-Tur (Bukit)":"52",
        "An-Najm (Binatang)":"53",
        "Al-Qamar (Bulan)":"54",
        "Ar-Rahman (Yang Maha Pemurah)":"55",
        "Al-Waqi’ah (Hari Kiamat)":"56",
        "Al-Hadid (Besi)":"57",
        "Al-Mujadilah (Wanita Yang Mengajukan Gugatan)":"58",
        "Al-Hasyr (Pengusiran)":"59",
        "Al-Mumtahanah (Wanita Yang Diuji)":"60",
        }
